name: Validate Flair

on:
  push:
    paths:
      - '.github/workflows/flair.yml'
      - 'public/flair/**'
  pull_request:
    paths:
      - '.github/workflows/flair.yml'
      - 'public/flair/**'

jobs:
  validate-flair:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: sudo apt-get update && sudo apt-get install -y imagemagick
      - run: ./bin/validate-flair public/flair/img/
